services:
  net.webapi.skeleton.web:
    container_name: Net.WebApi.Skeleton.Web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYCLOAK__AUTHSERVERURL=http://192.168.0.56:18080
      - KEYCLOAK__REALM=skeleton
      - KEYCLOAK__CLIENTID=webapi
    ports:
      - "5001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  keycloak:
    container_name: Keycloak
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "18080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
